### ISSUE TITLE
User needs a long rest to heal and regain spell slots and abilities.

### ISSUE THREAD

**Issue by itsmealexb** [chrisman/skookums-and-dragons#6]
Given: User is damaged and without spell slots & abilities

When: User rests for uninterupted 8 hours

Then: 
- User heals
- User gets spell slots back
- User's abilities recharge

**Comment by chrisman** [comment]
Partially successful. Some of the group rested, some were interrupted by the arrival of a friggin dragon

**Comment by chrisman** [comment]
closed in an adorable way in the [epilogue of ep06](https://github.com/chrisman/skookums-and-dragons/wiki/06-phandelin-run#epilogue)
